### ISSUE TITLE
Fix for using LEDs without the I2C I/O extender

### ISSUE THREAD

**Issue by pavel-a** [STMicroelectronics/stm32h743i-eval#1]
https://github.com/STMicroelectronics/stm32h743i-eval-bsp/blob/747aad83bba6dda3ac7f46576be5cfb14c02263e/stm32h743i_eval.c#L99

Please see https://github.com/STMicroelectronics/STM32CubeH7/issues/201
Move that issue here. Still not fixed in CubeH7 v.1.11.0

**Comment by HBOSTM** [comment]
hello @pavel-a ,

This point has been reported, it will be fixed in the next release.

Best Regards,

**Comment by HBOSTM** [comment]
ST Internal Reference: 126180

**Comment by ALABSTM** [comment]
Fixed in commit 61c958a96b14d4f820cac6a573025055ab73811f

**Comment by ALABSTM** [comment]
Hi @pavel-a,

I hope you are doing well. Just to let you know a fix has been uploaded. Thank you for your patience and thank you again for having reported.

With regards,
