### ISSUE TITLE
stm32h74x eval BSP, stm32h743i_eval_sd.c, stm32h747i_eval_sd.c  - sd card detection BUG

### ISSUE THREAD

**Issue by OriginalGreenGuy** [STMicroelectronics/stm32h743i-eval#2]
Setup:
Using STM32H743i-EVAL
Using STM32H743-FW-V1.11.0
file: stm32h743i_eval_sd.c, line 429
file: stm32h747i_eval_sd.c, line 434

BUG:
while calling the BSP_SD_DetectITConfig() function to set the edge detection for the SD card switch, the function always set the edge to rising regardless of the switch state.  This results in detecting  the card removal but never the card insertion.
The Bug is caused by improper use of "&&".  In this case it should be "&".
  
In both files, the statement should read:
 if(((uint32_t)BSP_IO_ReadPin(0, PinDetect[Instance]) & PinDetect[Instance]) != PinDetect[Instance])

**Comment by HBOSTM** [comment]
Hello @OriginalGreenGuy,

Firstly, thank you for this contribution. There is no problem in the SD card demo on my side, however it is the BSP_SD_DetectCallback function that is responsible for detecting the presence of the SD card and not BSP_SD_DetectITConfig.
So, please allow me to close this issue and thank you again for your contribution.

Best Regards,
