### ISSUE TITLE
Wrong core

### ISSUE THREAD

**Issue by carlo-dev-git** [STMicroelectronics/stm32h743i-eval#3]
FreeRTOS examples are using the CM4F port.
`<..>/Middlewares/Third_Party/FreeRTOS/Source/portable/RVDS/ARM_CM4F/port.c`
Why don't they use the CM7 port?
`<..>/Middlewares/Third_Party/FreeRTOS/Source/portable/RVDS/ARM_CM7/r0p1/port.c`

**Comment by HBOSTM** [comment]
Hello @carlo-dev-git ,

There are two options for running FreeRTOS on ARM Cortex-M7 microcontrollers.
The best option depends on the revision of the ARM Cortex-M7 core in use.
If the revision of the ARM Cortex-M7 core is not r0p1 then either option can be used, but it is recommended to use the FreeRTOS ARM Cortex-M4F port located in the /FreeRTOS/Source/portable/IAR/ARM_CM4F directory.

If the revision of the ARM Cortex-M7 core is r0p1 then use the FreeRTOS ARM Cortex-M7 r0p1 port located in the /FreeRTOS/Source/portable/IAR/ARM_CM7/r0p1 directory.

Best Regards,

**Comment by HBOSTM** [comment]
Hello @carlo-dev-git ,

Thank you for this contribution.
Please allow me to close this thread as answered. You may reopen it at anytime if you have any details to share with us in order to help you to solve the issue. Thank you for your comprehension.

With regards,
