### ISSUE TITLE
LCD Reset bug disables Ethernet

### ISSUE THREAD

**Issue by gregreenwood** [STMicroelectronics/stm32h743i-eval#4]
STM32H743i_eval_lcd.c V3.3.1
The eval board does not have a reset line for the LCD device and if the reset function at line 242 is called it will try to use initialize and use PA2 as the reset line which is used by the RMII ethernet for MDIO.  This will prevent the ethernet phy from working correctly.
At the very least this line should be commented out.  Better still would be to remove the line and all code associated with initializing PA2 for use by the LCD which is found between lines 399 and 417.  It would also be good to remove all associated lines in the .h file for the defines used by the code so no one will question the relevance of an LCD reset.

**Comment by ASEHSTM** [comment]
ST Internal Reference: 176453

**Comment by RJMSTM** [comment]
Fixed in : https://github.com/STMicroelectronics/stm32h743i-eval-bsp/commit/5ae5d39c0dbb87c49a3d3a59b54bbd4ac84e1873
